version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 3001:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
  service1:
    build: service1
    volumes:
      - ./log:/app/log
    links:
      - rabbitmq
    environment:
      - RABBITMQ_DEFAULT_HOST=rabbitmq
      - APIPORT=3002
    ports:
      - 3002:3002
    depends_on:
      rabbitmq:
        condition: service_healthy
  service2:
    build: service2
    volumes:
      - ./log:/app/log
    environment:
      - RABBITMQ_DEFAULT_HOST=rabbitmq
    links:
      - rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
